### ISSUE TITLE
Is there any option/rule to block <sql> tag ?

### ISSUE THREAD

**Issue by sudarshanaks** [whiteclarkegroup/liquibase-linter#79]
Hello,
I'm looking for a rule to lint <sql> tag present in xml . Do I need write custom rules?

**Comment by davidjgoss** [comment]
I think that should be a core rule called `no-raw-sql`, should also disallow `sqlFile`.

We'll try and get this in before the next release - unless you'd be willing to do a PR in the meantime

**Comment by davidjgoss** [comment]
I should say, whilst I think it merits having a core rule - because it will have a targeted message, and a documentation page that can spell out the reasons, etc - you can achieve this today with the "illegal-change-types" rule:
https://whiteclarkegroup.github.io/liquibase-linter/docs/rules/illegal-change-types

Something like:

```json
{
    "rules": {
        "illegal-change-types": {
            "values": ["sql", "sqlFile"]
        }
    }
}
```
