### ISSUE TITLE
Is there any way to  use two different linting profiles with two different linting file?  

### ISSUE THREAD

**Issue by sudarshanaks** [whiteclarkegroup/liquibase-linter#83]
Currently I need two lining profile to use liquibase linter for 
1. Admin changes which allows sql tag
2. developer changes which shouldn't allow sql tag
I already have a work around by using two separate liquibase installation directory by I'm looking is there any way to pass liquibase linter file name from command line.

**Comment by davidjgoss** [comment]
@sudarshanaks would be good to understand more about how you separate these two types of change in your project - do they use:

- Different context(s)?
- Different directory path?

**Comment by sudarshanaks** [comment]
> @sudarshanaks would be good to understand more about how you separate these two types of change in your project - do they use:
> 
> * Different context(s)?
> * Different directory path?

I have separate git branch and jenkins jobs for two different use cases as I mentioned

**Comment by davidjgoss** [comment]
@sudarshanaks ah okay, I sort of meant prior to your workaround.

Anyway, your use case sounds like a natural fit for [contexts](https://www.liquibase.org/documentation/contexts.html) in Liquibase, so you could locate your changes in the same branch of the same project, but have an "admin" context for the admin changes, you could then use that context to run them separately on Jenkins if that's still what you need.

For restricting the usage of `<sql>` changes to admin only, you could then use a combination of the [`illegal-change-types` rule](https://whiteclarkegroup.github.io/liquibase-linter/docs/rules/illegal-change-types) and a [`condition` expression](https://whiteclarkegroup.github.io/liquibase-linter/docs/rules/#options):

```json
{
    "rules": {
        "illegal-change-types": {
            "values": ["sql"],
            "condition": "!(getChangeSet().getContexts().getContexts().contains(\"admin\"))"
        }
    }
}
```

So then an admin change that does raw SQL would have to be something like:

```xml
<changeSet id="201912111234" author="sudarshanaks" context="admin">
    <sql>DELETE FROM IMPORTANT_TABLE</sql>
</changeSet>
```

And not having the "admin" context would cause the rule to be run and then fail.

Admittedly it's not super clean - we could probably do with a nicer way to check contexts in the `condition` expressions, so I'll create a separate issue for that, but hopefully this solves your problem short-term - let me know.

To your original question, I'm not sure we'll ever want to add a "profiles" concept, since IMO it would be duplicating what Liquibase itself already offers in the contexts feature.

**Comment by sudarshanaks** [comment]
But this option has one drawback if developer is smart enough to add "admin" context in xml file then it might execute. Currently  I created another lib folder with libsql and added another linting file and created another shell script(liquibasesql) from "liquibase" shell script to add jar files from libsql folder.

**Comment by davidjgoss** [comment]
Closing an effectively a dup of #91
